# neanno config file for airline_tickets sample

dataset:
    source: csv:samples/airline_tickets/texts.csv
    text_column: Text
    is_annotated_column: is_text_annotated
    target: csv:samples/airline_tickets/texts.annotated.csv

categories:
  definitions:
    - name: Ticketing
    - name: Service Offering
    - name: Technology
    - name: Mileage Plan
    - name: Security
    - name: Customs
    - name: Legal
    - name: Complaint
    - name: Misc
  column: categories

tagging:
  # shortcuts:
  #   anonymous: Alt+1
  #   named: Alt+2
  backcolor: "#333333"
  forecolor: "#50e6ff"

named_entities:
  definitions:
      - code: FROM
        shortcut: Alt+F
        # maincolor: "#ff8c31"
        # backcolor: "#333333"
        # forecolor: "#ff8c31"
      - code: TO
        shortcut: Alt+T
      - code: AIRLINE
        shortcut: Alt+A
      - code: AIRCRAFT
        shortcut: Alt+C
      - code: AIRPORT
        shortcut: Alt+I
  auto_suggest:
    sources:
      - csv:samples/airline_tickets/airlines.autosuggest.csv
      #- csv:samples/airline_tickets/airport_codes.autosuggest.csv
      #- csv:samples/airline_tickets/topics.autosuggest.csv
    regexes:
      - entity: AIRCRAFT
        pattern: (A\s*)?3[28]0|(B\s*)?7\d7(-\d{3})|CRJ|MD-\d{2}?

#spacy:
#  source: blank:en
#  target: models/airline_tickets