# neanno config file for airline_tickets sample

# notes: - this file contains a few settings which have been commented out.
#          these comments are included intentionally to show what other
#          configuration options exist.
#        - categories, key_terms, named_entities, spacy, instructions nodes
#          are optional. if they are not specified, neanno will disable the
#          respective features.

dataset:
    source: csv:samples/airline_tickets/texts.csv
    text_column: Text
    is_annotated_column: is_text_annotated
    target: csv:samples/airline_tickets/texts.annotated.csv

categories:
  definitions:
    - name: Ticketing
    - name: Service Offering
    - name: Technology
    - name: Mileage Plan
    - name: Security
    - name: Customs
    - name: Legal
    - name: Complaint
    - name: Misc
  column: categories

key_terms:
  auto_suggest:
    source:
      spec: csv:samples/airline_tickets/key_terms.autosuggest.csv
      writeback: True # TODO: implement writeback
    regexes:
      - description: terminals
        pattern: (?i)terminal\s*\d+\b
    #  - description: Just another sample, maybe not that useful
    #    pattern: (Hi|Hey|Hello) all
    #    parent_terms: Greeting, Hello
  # shortcuts:
  #   standalone: Alt+1
  #   parented: Alt+2
  #backcolor: "#333333"
  #forecolor: "#50e6ff"

named_entities:
  definitions:
      - code: FROM
        shortcut: Alt+F
        # maincolor: "#ff8c31"
        # backcolor: "#333333"
        # forecolor: "#ff8c31"
      - code: TO
        shortcut: Alt+T
      - code: AIRLINE
        shortcut: Alt+A
      - code: AIRCRAFT
        shortcut: Alt+C
      - code: TIME
        shortcut: Alt+E
  auto_suggest:
    sources:
      - csv:samples/airline_tickets/airlines.autosuggest.csv
    regexes:
      - entity: AIRCRAFT
        pattern: (A\s*)?3[28]0|(B\s*)?7\d7(-\d{3})|(Boeing\s*)?7\d7(-\d{3})CRJ|MD-\d{2}?
      - entity: TIME
        pattern: "(?x)
                   January \\b | Jan \\b | February \\b | Feb \\b | March \\b | Mar \\b | April \\b | Apr \\b
                  | May \\b | June \\b | Jun \\b | July \\b | Jul \\b | August \\b | Aug \\b | September \\b
                  | Sep \\b | October \\b | Oct \\b | November \\b | Nov \\b | December \\b | Dec \\b
                  | \\b(([01]?[0-9])|(2[0-3]))[:\\.]?[0-5][0-9]\\s*([Aa]\\.?[Mm]\\.?|[Pp]\\.?[Mm]\\.?|hrs)\\b
                 "

#spacy:
#  source: blank:en
#  target: models/airline_tickets

instructions: "
Put your instructions for the annotators here.
<br/>
You can even use <b>HTML</b>.
"