dataset:
    source: csv:samples/airline_tickets/texts.csv
    text_column: Text
    is_annotated_column: is_text_annotated
    target: csv:samples/airline_tickets/texts.annotated.csv

named_entities:
  definitions:
      - code: AIRLINE
        shortcut: Alt+A
        # color: "#456789"
      - code: AIRCRAFT
        shortcut: Alt+C
      - code: AIRPORT
        shortcut: Alt+P
      - code: TOPIC
        shortcut: Alt+T
  auto_suggest:
    sources:
        - csv:samples/airline_tickets/airlines.autosuggest.csv
        - csv:samples/airline_tickets/airport_codes.autosuggest.csv
        - csv:samples/airline_tickets/topics.autosuggest.csv

categories:
  definitions:
    - name: Ticketing
    - name: Timing
    - name: Service Offering
    - name: Mileage Plan
    - name: Security
    - name: Customs
    - name: Legal
    - name: Complaint
    - name: Misc
  column: categories

#spacy:
#  source: blank:en
#  target: models/airline_tickets