# neanno config file for meals sample

dataset:
    source: csv:samples/meals/sample_posts.csv
    text_column: post_text
    is_annotated_column: is_post_annotated
    target: csv:samples/meals/sample_posts.annotated.csv

named_entities:
  definitions:
      - code: MEAL
        shortcut: Alt+M
      - code: SIDE
        shortcut: Alt+S
      - code: APPETIZER
        shortcut: Alt+A
      - code: DESSERT
        shortcut: Alt+D
      - code: BEVERAGE
        shortcut: Alt+B