dataset:
    type: dict
    schema:
        source:
            type: string
            required: True
            regex: "^.+?:.+"
        text_column:
            type: string
            required: True
        is_annotated_column:
            type: string
            required: True
        target:
            type: string
            required: False
            regex: "^.+?:.+"
    required: True

categories:
    type: dict
    schema:
        definitions:
            type: list
            schema:
                type: dict
                schema:
                    name:
                        type: string
                        required: True
        column:
            type: string
            required: True
    required: False

key_terms:
    type: dict
    schema:
        shortcuts:
            type: dict
            schema:
                anonymous:
                    type: string
                    required: False
                child:
                    type: string
                    required: False
        backcolor:
            type: string
            regex: "(?i)^#[A-F0-9]{6}$|^[A-Z]+$"
            required: False
        forecolor:
            type: string
            regex: "(?i)^#[A-F0-9]{6}$|^[A-Z]+$"
            required: False
    nullable: True
    required: False

named_entities:
    type: dict
    schema:
        definitions:
            type: list
            schema:
                type: dict
                schema:
                    code:
                        type: string
                        required: True
                    shortcut:
                        type: string
                        required: True
                    color:
                        type: string
                        regex: "(?i)^#[A-F0-9]{6}$|^[A-Z]+$"
                        required: False
        auto_suggest:
            type: dict
            schema:
                sources:
                    type: list
                    schema:
                        type: string
                        regex: "^.+?:.+"
                regexes:
                    type: list
                    schema:
                        type: dict
                        schema:
                            entity:
                                type: string
                                required: True
                            pattern:
                                type: string
                                required: True
                        required: False
            required: False
    required: False

spacy:
    type: dict
    schema:
        source:
            type: string
            required: True
        target:
            type: string
            required: False
    required: False

instructions:
    type: string
    required: False